### ISSUE TITLE
inconsistent drop target

### ISSUE THREAD

**Issue by Leonidnei** [michaelmalonenz/aurelia-dragula#13] opened 2016-04-26 10:27 UTC
I have an application that displays list of items. When I dragging an item along the list, the UI shows the item moved to corresponding place in the list. Then I drop the item and "drop-fn" method handles the view model.

My problem is that target passed to drop-fn is not consistent: sometimes it is item before the dropped location and sometimes item after the location. Therefore I cannot handle list reorder.

**Comment by michaelmalonenz** [comment] 2016-04-26 11:01
are you able to show me the code for how you are using the library?  This isn't behaviour I've observed, so I don't know how I might go about reproducing it.  Ideally the view and the viewmodel code

**Comment by Leonidnei** [comment] 2016-04-26 11:04
How can I show the code? I can send you the view/VM where this happens but I do not think it worth to invest time to understand the code.

Can you explain how it is supposed to work? If drag 'a' between 'b' and 'c', what will be the target?

**Comment by michaelmalonenz** [comment] 2016-04-26 20:16
I've had a thought - either you didn't mean to say target, or target is the wrong parameter to be using.  Target should be the container that the item being dragged is dropped into.  If you have each item set up as a drop target, then I'm not sure what would happen - having inconsistent results is probably not surprising.  The parameter you should use is the `sibling` which should always be the following sibling or null if the item is being dropped at the end of the list.

The other thing to check is that the `direction` is set appropriately - the code for deciding the sibling can get quite confused when that is wrong.

Also, the whole library is about dragging 'a' between 'b' and 'c' - I can't summarise it without potentially missing important details for your situation, because I don't know your situation.

What I do know is that re-ordering is the primary reason I started using the original library, and made this port, so I know that it works for that use case (in a commercial environment).

**Comment by Leonidnei** [comment] 2016-04-27 10:43
Yes, I meant 'target' since I defined drag-source for all draggable items and drop-target for all places to where I can drag them. This works fine except for the problem we discussed and when I tried to define drop-target for the whole pane instead of items, dragging did not work good (although sibling was passed to itemDropped method).

It is very strange that the component does not pass consistent element on drop, this makes it unusable for us.

**Comment by michaelmalonenz** [comment] 2016-04-27 20:45
Righto, there seems to be a miscommunication somewhere.  'drag-source' and 'drop-target' are meant to be container elements that contain the items - that's how the library figures out which elements are to be dragged and dropped - the top-level children of those elements.  e.g.

```html
<dragula-and-drop drop-fn.call="dropFunction(item, target, source, sibling)"></dragula-and-drop>
<ul class="drop-target drag-source">
  <li>Item 1.</li>
  <li>Item 2.</li>
  <li>Item 3.</li>
  <li>Item 4.</li>
  <li>Item 5.</li>
</ul>
```

The above is the setup necessary to re-order plain html elements in an unordered list.

when dragging, the item would be an `<li>` element, the source and target would be the `<ul>` element and the sibling would either be the following `<li>` in the list of the place where it is being dropped or `null` if it is being dropped at the end.

I believe that the names of the parameters are consistent across the API, but if it isn't usable for you, then that's sad, but understandable.  I will therefore close the issue.

**Closed by michaelmalonenz** 2016-04-27 20:45 UTC
