### ISSUE TITLE
getting 404 on dragula.css.js

### ISSUE THREAD

**Issue by Leonidnei** [michaelmalonenz/aurelia-dragula#10] opened 2016-04-21 11:51 UTC
I'm trying to use aurelia-dragula in our project but getting:
system.js:4 GET http://localhost/WPL/jspm_packages/npm/aurelia-dragula@1.0.4/dragula.css.js 404 (Not Found)
so it appends '.js' to css file.

How I get rid of this?

**Comment by michaelmalonenz** [comment] 2016-04-22 21:28
That sort of issue is usually a misconfiguration of jspm.
If you can give me some more context I will try and help you out, but in the mean time, I'm going to close the issue as it is nothing to do with how I've packaged aurelia-dragula.

**Closed by michaelmalonenz** 2016-04-22 21:28 UTC

**Comment by michaelmalonenz** [comment] 2016-04-22 21:30
and by context, I mean:
- Have you bundled your app?
  - and if so, how are your bundles configured?
- Which version of aurelia-framework are you using?
- Which version of jspm are you using?

**Comment by Leonidnei** [comment] 2016-04-24 06:01
Here are the asnwers:

The problem happens on unbundled application.
aurelia-framework is beta.1.2.1
jspm is 0.16.29, I updated it to 0.16.33, but this did not help.

I tried aurelia-dragula sample application, it worked,so I did not find what is the difference.

The problem happens when I add aurelia-dragula plugin to main.js even before any change in the application code.

I'm attaching my config.js
[config.js.txt](https://github.com/michaelmalonenz/aurelia-dragula/files/233307/config.js.txt)

**Comment by michaelmalonenz** [comment] 2016-04-24 06:24
Hmm.  That all looks like it should work.  I'm confused as well.  Are you able to reproduce it in a reduced skeleton so I can take a proper look?

**Comment by markadrake** [comment] 2016-06-17 00:46
Hi @michaelmalonenz 

If you could walk me through the steps on how I could provide you some more information about this bug I'd be happy to report it back here. I'm afraid I'm dabbling in Node and Aurelia for the first time and not very experienced - however I've ran into this exact problem tonight when trying to add your plugin to my aurelia project.

Node v4.3.2
NPM v3.8.1
Aurelia v1.0.0-beta.2.0.1

I ran the following to install your package:

```
jspm install npm:aurelia-dragula
```

I then added the plugin to the main.js file:

```
aurelia.use.plugin('aurelia-dragula');
```

At this point, even before the rest of the implementation I received the following console error in the browser:

```
system.js:123 Uncaught (in promise) Error: (SystemJS) Error: XHR error (404 Not Found) loading http://localhost:3000/src/css.js
	Error loading http://localhost:3000/src/css.js
	Error loading http://localhost:3000/jspm_packages/npm/aurelia-dragula@1.2.0/dragula.css!http://localhost:3000/src/css.js as "./dragula.css!css" from http://localhost:3000/jspm_packages/npm/aurelia-dragula@1.2.0/dragula-and-drop.js
```

I've verified that the path `jspm_packages/npm/aurelia-dragula@1.2.0/dragula-and-drop.js` exists in my project. I'm not sure how I'd t/s this on my own.

Is anyone else have this issue?

Let me know if there is anything else I can do on my end to help you track this bug down.

Thanks

**Comment by michaelmalonenz** [comment] 2016-06-17 01:33
I expect that you just need to install the text plugin for systemjs. `jspm
install text` should do the trick.

I tried to add it as a dependency, but systemjs was not happy about it.
Sorry for the confusion - I'll add a note to the docs.

Michael

**Comment by michaelmalonenz** [comment] 2016-06-17 21:51
and by text plugin, I meant the css plugin.

`jspm install css`
