### ISSUE TITLE
Dragula crashes when dragged element is removed

### ISSUE THREAD

**Issue by rafatpc** [michaelmalonenz/aurelia-dragula#32] opened 2017-03-20 11:07 UTC
Hey guys,

I've just occurred that bug. When I start dragging element and it disappear from the DOM (dynamically) when you attempt to drop the element the following error occurs:
```
Uncaught DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at Dragula.cancel
    at DragulaAndDrop._dropFunction
    at Array.forEach (native)
    at Emitter.emit
    at Dragula.drop
    at Dragula._release
```
I'm using the "dragula-and-drop" custom element. Is there a temporary workaround which you can think of? And can you please look at the issue?

Regards,
Liliyan

**Comment by michaelmalonenz** [comment] 2017-03-21 22:52
Hi Liliyan,

There's a bit of a disconnect in how dragula functions.  There are a couple of different possibilities here, but the most likely, is that you're removing the element during the drop function.  Dragula doesn't like that.  If you really want to remove the element during drop, then I'll have to working something out.

Could you please provide a small reproduction, to ensure we are definitely talking about the same issue?

Michael

**Comment by michaelmalonenz** [comment] 2017-05-17 09:24
Closing due to lack of interest.  Please re-open if you come up with more information for me

**Closed by michaelmalonenz** 2017-05-17 09:24 UTC
