### ISSUE TITLE
Error when using the plugin with the new Aurelia CLI

### ISSUE THREAD

**Issue by wasimf** [michaelmalonenz/aurelia-dragula#19] opened 2016-08-15 07:21 UTC
Hi ,

I'm creating a new project of Aurelia with the CLI tool (au new) with typescript template.
I installed aurelia-dragula with npm and start using it in my typescript files. 
When I run "au run --watch" , I get an error " [Error: ENOENT: no such file or directory, open 'C:\temp\client\src\dragula.js']"
If I open my ts file , I have a problem with the import statement "import {dragula} from 'dragula';"
Module ''dragula'' has no exported member dragula

Any idea please ? Did you use this plugin with the new Aurelia CLI project .

Thanks in advance ...

**Comment by michaelmalonenz** [comment] 2016-08-15 10:48
I don't export anything named `dragula`.  There is the class `Dragula` and it would be exported from `aurelia-dragula`, not `dragula`. 

Though I strongly recommend using the custom element, rather than importing the code directly.

**Comment by eriklieben** [comment] 2016-09-08 19:27
If you add it in this way, it seems to work:

```javascript
          {
              "name": "aurelia-dragula",
              "path": "../node_modules/aurelia-dragula/dist/amd",
              "main": "index"
          },
```
Typescript will still complain/show warning about missing definitions, but it compiles.

**Comment by michaelmalonenz** [comment] 2016-09-09 07:31
I don't actually know how to generate / create typescript definitions, so if anyone wants to help in that department, I will gladly accept pull requests.  Or just drop some hints in this issue - anything would be appreciated

**Comment by michaelmalonenz** [comment] 2016-10-03 07:09
As I've included the TS definitions (thanks to @eriklieben) I'm going to close this issue (especially as I'm not sure it was entirely caused by missing TS defs, either.)  If you have ongoing problems, please raise another issue with specific details

**Closed by michaelmalonenz** 2016-10-03 07:09 UTC
